export const langs = {
    afr: "Afrikaans",
    alb: "Albanian",
    alg: "Algonquian languages",
    alt: "Southern altai",
    amh: "Amharic",
    ang: "Old english",
    ara: "Arabic",
    arm: "Armenian",
    asm: "Assamese",
    aus: "Australian languages",
    aym: "Aymara",
    aze: "Azerbaijani",
    bak: "Bashkir",
    bam: "Bambara",
    baq: "Basque",
    bel: "Belarusian",
    ben: "Bangla",
    bnt: "Bantu languages",
    bos: "Bosnian",
    bre: "Breton",
    bul: "Bulgarian",
    bur: "Burmese",
    cat: "Catalan",
    cau: "Caucasian languages",
    ceb: "Cebuano",
    chi: "Chinese",
    chv: "Chuvash",
    cmn: "Mandarin chinese",
    cor: "Cornish",
    cpe: "English-based creoles and pidgins",
    crp: "Creoles and pidgins",
    cze: "Czech",
    dan: "Danish",
    dra: "Dravidian languages",
    dut: "Dutch",
    efi: "Efik",
    egy: "Ancient egyptian",
    eng: "English",
    enm: "Middle english",
    epo: "Esperanto",
    esk: "Northwest alaska inupiatun",
    est: "Estonian",
    fao: "Faroese",
    fat: "Fanti",
    fin: "Finnish",
    fiu: "Finno-ugrian languages",
    fon: "Fon",
    fre: "French",
    frm: "Middle french",
    fro: "Old french",
    fry: "Western frisian",
    ful: "Fula",
    gem: "Germanic languages",
    geo: "Georgian",
    ger: "German",
    gez: "Geez",
    gla: "Scottish gaelic",
    gle: "Irish",
    glg: "Galician",
    gmh: "Middle high german",
    gon: "Gondi",
    grc: "Ancient greek",
    gre: "Greek",
    guj: "Gujarati",
    hat: "Haitian creole",
    haw: "Hawaiian",
    hbs: "Serbian (latin)",
    heb: "Hebrew",
    him: "Himachali languages",
    hin: "Hindi",
    hrv: "Croatian",
    hun: "Hungarian",
    ice: "Icelandic",
    ina: "Interlingua",
    inc: "Indic languages",
    ind: "Indonesian",
    ira: "Iranian languages",
    iro: "Iroquoian languages",
    ita: "Italian",
    jpn: "Japanese",
    kaa: "Kara-kalpak",
    kab: "Kabyle",
    kal: "Kalaallisut",
    kan: "Kannada",
    kaz: "Kazakh",
    khm: "Khmer",
    kin: "Kinyarwanda",
    kir: "Kyrgyz",
    kor: "Korean",
    kru: "Kurukh",
    kum: "Kumyk",
    kur: "Kurdish",
    lad: "Ladino",
    lao: "Lao",
    lat: "Latin",
    lav: "Latvian",
    lit: "Lithuanian",
    ltz: "Luxembourgish",
    lug: "Ganda",
    lus: "Mizo",
    mac: "Macedonian",
    mal: "Malayalam",
    mao: "Māori",
    map: "Austronesian languages",
    mar: "Marathi",
    may: "Malay",
    mis: "Uncoded languages",
    mlt: "Maltese",
    mon: "Mongolian",
    mul: "Multiple languages",
    myn: "Mayan languages",
    nai: "North american indian languages",
    nep: "Nepali",
    new: "Newari",
    nic: "Niger-kordofanian languages",
    nno: "Norwegian nynorsk",
    nob: "Norwegian bokmål",
    nor: "Norwegian",
    nso: "Northern sotho",
    nya: "Nyanja",
    ori: "Odia",
    orm: "Oromo",
    oss: "Ossetic",
    ota: "Ottoman turkish",
    paa: "Papuan languages",
    pan: "Punjabi",
    per: "Persian",
    pol: "Polish",
    por: "Portuguese",
    pus: "Pashto",
    roa: "Romance languages",
    roh: "Romansh",
    rom: "Romany",
    rum: "Romanian",
    rus: "Russian",
    sah: "Yakut",
    san: "Sanskrit",
    sco: "Scots",
    sin: "Sinhala",
    sit: "Sino-tibetan languages",
    sla: "Slavic languages",
    slo: "Slovak",
    slv: "Slovenian",
    smo: "Samoan",
    snd: "Sindhi",
    snk: "Soninke",
    som: "Somali",
    sot: "Southern sotho",
    spa: "Spanish",
    srp: "Serbian",
    ssw: "Swati",
    swa: "Swahili",
    swe: "Swedish",
    syr: "Syriac",
    tam: "Tamil",
    tat: "Tatar",
    tel: "Telugu",
    tgk: "Tajik",
    tgl: "Filipino",
    tha: "Thai",
    tib: "Tibetan",
    tig: "Tigre",
    ton: "Tongan",
    tsn: "Tswana",
    tuk: "Turkmen",
    tur: "Turkish",
    uig: "Uyghur",
    ukr: "Ukrainian",
    und: "Unknown language",
    urd: "Urdu",
    uzb: "Uzbek",
    vie: "Vietnamese",
    vls: "West flemish",
    wel: "Welsh",
    wol: "Wolof",
    xho: "Xhosa",
    yid: "Yiddish",
    yor: "Yoruba",
    zap: "Zapotec",
}